name: ${project.name}
main: vg.civcraft.mc.citadel.Citadel
version: ${project.version}
author: Rourke750
depend: [NameLayer, CivModCore]
softdepend: [Mercury, BetterShards]
description: Citadel allows you to make blocks difficult to break. When a block is reinforced, it must be broken many times before it is destroyed.
commands:
 ctr:
  aliases: [ctreinforce, reinforce, protect, cprivate, lwc, private]
 ctacid:
 ctf:
  aliases: [ctfortify, fortify]
 ctb:
  aliases: [ctbypass, bypass]
 cti:
  aliases: [ctinformation, info, ctinfo]
 ctin:
  aliases: [ctinsecure]
 ctm:
  aliases: [ctmaterials, materials]
 cto:
  aliases: [ctoff, off]
 cts:
  aliases: [ctstats]
  permission: citadel.admin
 ctur:
  permission: citadel.admin
 ctar:
  permission: citadel.admin
  aliases: [ctareareinforce] 
 ctsl:
  permission: citadel.admin
  aliases: [ctsetlogging]
 cte:
  aliases: [cteasy,toggleeasymode]
 ctdl:
  aliases: [reinforcements,rein]
permissions:
 citadel.admin:
  default: op
 citadel.admin.accesssecurable:
  default: op
