name: Citadel
main: vg.civcraft.mc.citadel.Citadel
version: 3.0.18
author: Rourke750
depend: [NameLayer]
commands:
 ctr:
  aliases: [ctreinforce]
 ctacid:
 ctf:
  aliases: [ctfortify]
 ctb:
  aliases: [ctbypass]
 cti:
  aliases: [ctinformation]
 ctin:
  aliases: [ctinsecure]
 ctm:
  aliases: [ctmaterials:]
 cto:
  aliases: [ctoff]
permissions:
 citadel.admin:
  default: op
 citadel.admin.accesssecurable:
  default: op